force-app/main/default/objects/Mukn_Setting__mdt/Mukn_Setting__mdt.object-meta.xml
<CustomObject>
    <label>MuKn Setting</label>
    <pluralLabel>MuKn Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Mukn_Setting__mdt/fields/MuKnWeb3CA_AppUrl__c.field-meta.xml
<CustomField>
    <fullName>MuKnWeb3CA_AppUrl__c</fullName>
    <description>The URL for the MuKn Web3 Crypto Account application.</description>
    <label>MuKn Web3 CA App URL</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mukn_Setting__mdt/fields/MuKnWeb3CA_SFDC_AppUrl__c.field-meta.xml
<CustomField>
    <fullName>MuKnWeb3CA_SFDC_AppUrl__c</fullName>
    <label>MuKnWeb3CA_SFDC_AppUrl</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MuknSettings.cls
public with sharing class MuknSettings {
    @TestVisible
    private static Mukn_Setting__mdt orgDefaultSettings {
        get {
            if (orgDefaultSettings == null) {
                orgDefaultSettings = Mukn_Setting__mdt.getInstance('Default');
            }
            return orgDefaultSettings;
        }
        set;
    }

    public static String muknCaAppUrl {
        get {
            return orgDefaultSettings.MuKnWeb3CA_AppUrl__c;
        }
    }

    public static String muknCaSFDCAppUrl {
        get {
            return orgDefaultSettings.MuKnWeb3CA_SFDC_AppUrl__c;
        }
    }
}