force-app/main/default/objects/Mukn_Setting__mdt/Mukn_Setting__mdt.object-meta.xml
<CustomObject>
    <label>MuKn Setting</label>
    <pluralLabel>MuKn Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Mukn_Setting__mdt/fields/MuKnWeb3CA_AppUrl__c.field-meta.xml
<CustomField>
    <fullName>MuKnWeb3CA_AppUrl__c</fullName>
    <description>The URL for the MuKn Web3 Crypto Account application.</description>
    <label>MuKn Web3 CA App URL</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mukn_Setting__mdt/fields/MuKnWeb3CA_SFDC_AppUrl__c.field-meta.xml
<CustomField>
    <fullName>MuKnWeb3CA_SFDC_AppUrl__c</fullName>
    <label>MuKnWeb3CA_SFDC_AppUrl</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
@NamespaceAccessible
@IsTest
public with sharing class TestDataFactory {
    @NamespaceAccessible
    public static Account createAccount(Boolean doInsert) {
        Account account = new Account();
        account.Name = 'test_account_name';

        if (doInsert) {
            insert account;
        }
        return account;
    }

    @NamespaceAccessible
    public static Mukn_Setting__mdt createMuknSettings() {
        Mukn_Setting__mdt settings = new Mukn_Setting__mdt(
            MuKnWeb3CA_AppUrl__c = 'mukn_app_url',
            MuKnWeb3CA_SFDC_AppUrl__c = 'mukn_sfdc_app_url'
        );

        return settings;
    }
}