force-app/main/default/objects/Web3EnablerSettings__c/Web3EnablerSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Web3EnablerSettings</label>
</CustomObject>

force-app/main/default/objects/Web3EnablerSettings__c/fields/Payment_Variance_Accepted__c.field-meta.xml
<CustomField>
    <fullName>Payment_Variance_Accepted__c</fullName>
    <label>Payment Variance Accepted</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/Web3EnablerSettingsService.cls
public without sharing class Web3EnablerSettingsService {
    private final static Decimal DEFAULT_PAYMENT_VARIANCE_ACCEPTED = 3;

    private Web3EnablerSettings__c settings;

    public Web3EnablerSettingsService() {
        settings = Web3EnablerSettings__c.getOrgDefaults();
    }

    // Web3 Payments
    public Decimal getPaymentVariance() {
        return settings.Payment_Variance_Accepted__c != null
            ? settings.Payment_Variance_Accepted__c
            : DEFAULT_PAYMENT_VARIANCE_ACCEPTED;
    }

    public void updatePaymentVariance(Decimal value) {
        settings.Payment_Variance_Accepted__c = value;
    }

    // Shared
    public void saveSettings() {
        upsert as system settings;
    }
}