force-app/main/default/objects/ExternalAPISettings__c/ExternalAPISettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>ExternalAPISettings</label>
</CustomObject>

force-app/main/default/objects/ExternalAPISettings__c/fields/CoinGeckoAPIKey__c.field-meta.xml
<CustomField>
    <fullName>CoinGeckoAPIKey__c</fullName>
    <label>CoinGecko API Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ExternalKeyService.cls
public without sharing class ExternalKeyService {
    private ExternalAPISettings__c apiSettings;

    public ExternalKeyService() {
        apiSettings = ExternalAPISettings__c.getOrgDefaults();
    }

    // CoinGecko
    public Boolean isCoinGeckoProEnabled() {
        return apiSettings.CoinGeckoAPIKey__c != null;
    }

    public String getCoinGeckoApiKey() {
        return apiSettings.CoinGeckoAPIKey__c != null ? apiSettings.CoinGeckoAPIKey__c : '';
    }

    public void updateCoinGeckoApiKey(String value) {
        apiSettings.CoinGeckoAPIKey__c = value;
    }

    // Shared
    public void saveSettings() {
        upsert as system apiSettings;
    }
}